repos:
  - repo: https://github.com/psf/black
    rev: "22.12.0"
    hooks:
      - id: black
        args:
          - --check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --follow-imports=silent
          - --install-types
          - --non-interactive
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.220"
    hooks:
      - id: ruff
        args: ["--select", "E,F,I001"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.29.0"
    hooks:
      - id: yamllint
        args: ["--config-file", ".yamllint.yaml"]
