[tool.isort]
profile = "black"
line_length = 88
skip = ["./.venv", "./direnv", ".env"]

[tool.cruft]
skip = ["src", "tests", ".git", ".mypy_cache", ".venv", ".direnv", ".env"]

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
(
  /(
      \.vscode
    | \.git
    | \.pytest_cache
    | \.mypy_cache
    | \.venv
    | \.env
    | \.direnv
  )/
)
'''

[tool.pytest.ini_options]
testpaths = ["src/intake_patterncatalog/tests"]

[tool.bumpver]
current_version = "2021.4.0"
version_pattern = "YYYY.MM.INC0[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]
"setup.py" = [
   "version=\"{version}\""
]
"src/intake_patterncatalog/__init__.py" = [
    "__version__ = \"{version}\""
]